name: CI/CD Local

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - run: docker build -t frontend:${{ github.run_number }} ./frontend

      - run: |
          kubectl set image deployment/frontend \
          app=frontend:${{ github.run_number }}

  deploy-api:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - run: docker build -t api:${{ github.run_number }} ./api

      - run: |
          kubectl set image deployment/api \
          app=api:${{ github.run_number }}
